// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TugasAkhir_VsCode.Data;

#nullable disable

namespace TugasAkhir_VsCode.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240202130326_Init table Database")]
    partial class InittableDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TugasAkhir_VsCode.Models.Items", b =>
                {
                    b.Property<string>("Kode_barang")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bahan")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DMODI")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("longtext");

                    b.Property<long>("Harga_jual")
                        .HasColumnType("bigint");

                    b.Property<long>("Harga_modal")
                        .HasColumnType("bigint");

                    b.Property<string>("Image1")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama_barang")
                        .HasColumnType("longtext");

                    b.Property<string>("PathImage1")
                        .HasColumnType("longtext");

                    b.Property<int>("Stok_barang")
                        .HasColumnType("int");

                    b.Property<string>("Ukuran")
                        .HasColumnType("longtext");

                    b.Property<string>("VMODI")
                        .HasColumnType("longtext");

                    b.Property<string>("Warna")
                        .HasColumnType("longtext");

                    b.HasKey("Kode_barang");

                    b.ToTable("tb_items");
                });

            modelBuilder.Entity("TugasAkhir_VsCode.Models.Roles", b =>
                {
                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("RolesId");

                    b.ToTable("tb_roles");
                });

            modelBuilder.Entity("TugasAkhir_VsCode.Models.Users", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("BgEffDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role_User")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("tb_users");

                    b.HasData(
                        new
                        {
                            UserId = "U0001",
                            BgEffDate = new DateTime(2024, 2, 2, 20, 3, 26, 154, DateTimeKind.Local).AddTicks(7145),
                            Name = "Administrator",
                            Password = "Admin2024",
                            Role_User = "Admin",
                            Status = "0",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
